[package]
name = "rustcool"
version = "0.0.0"
authors = ["mersinvald <me@mkl.dev>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
